adding init_cookies function
dfe-analytical-services/dfeshiny pull request #37
Opened 2024-05-13 14:23 UTC by jen-machin

Added init_cookies function and tried to account for scenarios where:

- JS file already exists
- JS file doesn't exist
- Download fails for some other reason (e.g. URL broken/user not connected to internet) 

I've tested each outcome and it does seem to work but I can easily be wrong!

2024-05-13 14:59 UTC, jen-machin commented
Have added in a function that creates the www/ folder if it doesn't already exist

2024-05-15 08:44 UTC, rmbielby commented on R/cookies.R
> +
I'd prefer not to have the whitespace lines here, looks a bit confusing like the roxygen comments aren't associated with the function.

2024-05-15 08:46 UTC, rmbielby commented on R/cookies.R
> +
init_cookies currently isn't exported as a user function, so won't work when people load the package. Need to add the @export line to the roxygen comments (can check the other functions for how it needs to be done).

2024-05-17 09:57 UTC, cjrace requested changes
I think you're missing some of the standard roxygen sections, have you ran devtools::check() locally to test the package on this branch? 

That should hopefully tell you the ones missing, off the top of my head, I know it usually expects @examples to present.

I think the checks won't run on the PR itself until you resolve the conflicts that exist too, so have a go at removing them and we'll be able to see if anything else comes up in the automated checks

2024-05-17 09:57 UTC, cjrace commented on R/cookies.R
> +#' Call init_cookies() in the console to run the function
For the example I'd do something like this probably so it shows in the standard way on the documentation
 
#' @examples
#' if (interactive()) {
#'   init_cookies()
#' }

2024-06-03 08:32 UTC, cjrace commented
![](https://github.trello.services/images/mini-trello-icon.png) [Finish init_cookies documentation](https://trello.com/c/y4UXBmwk/1359-finish-initcookies-documentation)

2024-06-03 13:33 UTC, cjrace commented on R/cookies.R
> +      download.file(url = "https://raw.githubusercontent.com/dfe-analytical-services/dfeshiny/main/inst/cookie-consent.js", destfile = "www/cookie-consent.js"),
As this is just a long url, I'd stick `# nolint: [line_length_linter]` at the end of the line and that will tell lintr to ignore the line length being long here.

It's either that or cut up the URL into chunks and paste together but that feels excessive

2024-06-03 13:33 UTC, cjrace commented on R/cookies.R
> +  if (!dir.exists(output_dir)){
Might be worth running `styler::style_pkg()` locally to see if it'll automatically clean this up?

2024-06-03 13:36 UTC, cjrace commented on R/cookies.R
> +  if (!dir.exists(output_dir)){
Might be worth running styler::style_pkg() locally to see if it'll automatically clean this up?

2024-06-03 13:37 UTC, cjrace commented on R/cookies.R
> +#' init_cookies() creates a local copy of the JavaScript file required for cookies to work.
I'd break this over two lines to hush the alert, should still render the same even if split over multiple lines

2024-06-03 13:37 UTC, cjrace commented on R/cookies.R
> +    tryCatch(
Might be worth running styler::style_pkg() locally to see if it'll automatically clean this up?

2024-06-05 11:39 UTC, jen-machin commented on R/cookies.R
> +      download.file(url = "https://raw.githubusercontent.com/dfe-analytical-services/dfeshiny/main/inst/cookie-consent.js", destfile = "www/cookie-consent.js"),
🙃

2024-07-02 10:17 UTC, rmbielby requested changes
Tested it within the package and loaded to another project and looks like it works well.

Handful of minor changes requested.

2024-07-02 10:17 UTC, rmbielby commented on R/cookies.R
> +#' It checks whether there is already a www/ folder and if not, it creates one
Can you add full-stops at the end of these lines. When it renders in a help page, it takes out the carriage returns and just flows on, which makes it awkward to read if there's no full-stops at the end of sentences.

2024-07-02 10:17 UTC, rmbielby commented on R/cookies.R
> +    print("Cookie script updated")
`message()` probably better to use than `print()` here.

2024-07-02 10:17 UTC, rmbielby commented on R/cookies.R
> +    print("www folder already exists!")
Probably better to use `message()` in place of `print()`.

2024-07-17 09:58 UTC, rmbielby approved these changes

2024-07-18 09:44 UTC, cjrace approved these changes
As mentioned on Trello, happy to approve given Rich is happy and I'll do a review of the examples and documentation in my follow up PR anyway too

2024-07-19 06:38 UTC, merged