initial commit dfe footer with connection to accessibility panel
dfe-analytical-services/dfeshiny pull request #71
Opened 2024-12-13 17:27 UTC by alex-rogers-hub

# Brief overview of changes
New script to add dfe footer with link to accessibility tab
...

## Why are these changes being made?

...

## Detailed description of changes

...

## Additional information for reviewers

...

## Issue ticket number/s and link
issue #85(https://github.com.mcas.ms/dfe-analytical-services/shiny-template/issues/85)
...

2024-12-16 09:03 UTC, rmbielby requested changes
Same as the previous one, please can you got through the steps of `styler::style_dir()`, `lintr::lint_dir()` and set up some basic tests for the function.

2024-12-16 17:42 UTC, alex-rogers-hub commented
lintr and styler run and updates pushed through

2024-12-19 17:27 UTC, rmbielby requested changes
Thanks for updating with those tests. Got a few more comments on how we can build the functionality a little bit.

2024-12-19 17:27 UTC, rmbielby commented on R/footer_dfe_auto.R
> +              shiny::actionLink("Accessibility", "Accessibility information")
This placement looks a bit odd. I think it needs to be higher up, like the footer in this example:
https://department-for-education.shinyapps.io/local-authority-interactive-tool/

2024-12-19 17:27 UTC, rmbielby commented on R/footer_dfe_auto.R
> +footer_dfe <- function(full = FALSE) {
It'd be helpful to be able to pass here a dynamic list of link names that the user wants putting in. We'd probably want the default to be along the lines of `c("Accessibility", "Support and feedback", "Cookies")`

Here's an example function from an existing dashboard:
https://github.com/dfe-analytical-services/local-authority-interactive-tool/blob/bb117d6d063a2a37a01722c4955169cc534b5b54/R/fn_ui_layout.R#L215

And how it then looks in the UI:
https://github.com/dfe-analytical-services/local-authority-interactive-tool/blob/bb117d6d063a2a37a01722c4955169cc534b5b54/ui.R#L145

2024-12-19 17:27 UTC, rmbielby commented on R/footer_dfe_auto.R
> +footer_dfe <- function(full = FALSE) {
For consistency with the `header`, I think let's stick to `footer` rather than `footer_dfe`.

2024-12-19 17:27 UTC, rmbielby commented on tests/testthat/test-test_footer_dfe_auto.R
> +test_that("outputs are as expected", {
Thanks for adding these. Next up, it'd be good to also add an example of it being implemented in the test dashboard:

https://github.com/dfe-analytical-services/dfeshiny/blob/main/tests/test_dashboard/ui.R

2024-12-30 11:23 UTC, cjrace commented
Looks like this has been a good learning experience so far! Worth checking this update to shinyGovstyle that I think does some of what this is starting to - https://github.com/dfe-analytical-services/shinyGovstyle/pull/114. I think the changes to address https://github.com/dfe-analytical-services/shiny-template/issues/85 could be made directly to the shiny template using shinyGovstyle after updating?

I think the shinyGovstyle changes also address some of your comments @rmbielby with the link placement and general HTML tagging using the GOV.UK footer links class - though worth giving it a check over once added into the shiny template.

2025-01-09 13:39 UTC, closed without merging